In [81]:
#Importation du bibliothèque pandas pour l'exécution du fichieier csv 
import pandas as pd 
import numpy as np

In [82]:
#lecture du fichier csv 

df= pd.read_csv(r"C:\Users\DELL\Downloads\classeur 1.csv")

In [83]:
#ligne et colonne
df.shape

(666, 34)

In [84]:
#Detection des valeurs manquantes 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 666 entries, 0 to 665
Data columns (total 34 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 666 non-null    int64
 1   Job title             666 non-null    object
 2   Salary Estimate       666 non-null    object
 3   Rating                617 non-null    float64
 4   SQL                   666 non-null    object
 5   Power BI              666 non-null    object
 6   AWS                   666 non-null    object
 7   Hadoop                666 non-null    object
 8   Spark                 666 non-null    object
 9   TensorFlow            666 non-null    object
 10  Tableau               666 non-null    object
 11  Microsoft tools       666 non-null    object
 12  Excel                 666 non-null    object
 13  Python                666 non-null    object
 14  Company Name          666 non-null    object
 15  Location              666 non-null    object
 16  Location initials     643 non-null    object
 17  Headquarters          666 non-null    object
 18  Headquarters Initial  636 non-null    object
 19  Size                  666 non-null    object
 20  Founded               666 non-null    int64
 21  Type of ownership     640 non-null    object
 22  Publicity             666 non-null    object
 23  Industry              666 non-null    object
 24  Sector                666 non-null    object
 25  Revenue               666 non-null    object
 26  no_of_competitors     666 non-null    int64
 27  YOE                   410 non-null    float64
 28  Computer Science      666 non-null    object
 29  Bachelor's            666 non-null    object
 30  Master's              666 non-null    object
 31  PhD                   666 non-null    object
 32  Statistics            666 non-null    object
 33  Mathematics           666 non-null    object
dtypes: float64(2), int64(3), object(29)
memory usage: 177.0+ KB

In [85]:
#nombres des valeurs null
df.isnull().sum()

index                     0
Job title                 0
Salary Estimate           0
Rating                   49
SQL                       0
Power BI                  0
AWS                       0
Hadoop                    0
Spark                     0
TensorFlow                0
Tableau                   0
Microsoft tools           0
Excel                     0
Python                    0
Company Name              0
Location                  0
Location initials        23
Headquarters              0
Headquarters Initial     30
Size                      0
Founded                   0
Type of ownership        26
Publicity                 0
Industry                  0
Sector                    0
Revenue                   0
no_of_competitors         0
YOE                     256
Computer Science          0
Bachelor's                0
Master's                  0
PhD                       0
Statistics                0
Mathematics               0
dtype: int64

In [86]:
#voir les doublons 

df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
661    False
662    False
663    False
664    False
665    False
Length: 666, dtype: bool

In [87]:
#supprimmer les doublons 

df.drop_duplicates()

,index,Job title,Salary Estimate,Rating,SQL,Power BI,AWS,Hadoop,Spark,TensorFlow,...,Sector,Revenue,no_of_competitors,YOE,Computer Science,Bachelor's,Master's,PhD,Statistics,Mathematics
0,0,Data Scientist,$137K-$171K,3.0,No,No,Yes,No,No,No,...,Insurance,Unknown,3,NaN,Yes,Yes,Yes,No,Yes,No
1,1,Data Scientist,$137K-$171K,4.0,Yes,No,No,Yes,No,No,...,Business Services,$1B-$2B,0,12.0,Yes,Yes,No,No,Yes,Yes
2,2,Data Scientist,$137K-$171K,4.0,No,No,Yes,No,No,No,...,Business Services,$100 M- $500 M,0,NaN,Yes,No,No,Yes,Yes,Yes
3,3,Data Scientist,$137K-$171K,4.0,Yes,No,Yes,No,No,Yes,...,Manufacturing,$100 M- $500 M,3,NaN,Yes,Yes,No,No,No,No
4,4,Data Scientist,$137K-$171K,3.0,Yes,No,No,No,No,No,...,Business Services,Unknown,3,NaN,Yes,No,No,No,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
661,667,Data Scientist,$105K-$167K,4.0,Yes,Yes,No,Yes,No,No,...,Business Services,Unknown,0,NaN,Yes,No,No,No,Yes,Yes
662,668,Data Scientist,$105K-$167K,NaN,No,No,No,No,No,No,...,Unknown,Unknown,0,NaN,No,No,No,No,No,No
663,669,Data Scientist,$105K-$167K,NaN,Yes,Yes,No,Yes,No,No,...,Unknown,Unknown,0,3.0,Yes,No,No,No,Yes,No
664,670,Data Scientist,$105K-$167K,5.0,Yes,No,No,Yes,Yes,Yes,...,Business Services,$1 M- $5 M,0,7.0,Yes,Yes,No,Yes,Yes,Yes
665,671,Data Scientist,$105K-$167K,3.0,Yes,No,No,No,No,No,...,Business Services,$1B-$2B,0,5.0,No,No,No,No,Yes,Yes

In [88]:
# renommer les colonnes pour les normaliser (minuscules, underscores, etc.)
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [89]:
df.columns

Index(['index', 'job_title', 'salary_estimate', 'rating', 'sql', 'power_bi',
       'aws', 'hadoop', 'spark', 'tensorflow', 'tableau', 'microsoft_tools',
       'excel', 'python', 'company_name', 'location', 'location_initials',
       'headquarters', 'headquarters_initial', 'size', 'founded',
       'type_of_ownership', 'publicity', 'industry', 'sector', 'revenue',
       'no_of_competitors', 'yoe', 'computer_science', 'bachelor's',
       'master's', 'phd', 'statistics', 'mathematics'],
      dtype='object')

In [90]:
df[df.columns]

,index,job_title,salary_estimate,rating,sql,power_bi,aws,hadoop,spark,tensorflow,...,sector,revenue,no_of_competitors,yoe,computer_science,bachelor's,master's,phd,statistics,mathematics
0,0,Data Scientist,$137K-$171K,3.0,No,No,Yes,No,No,No,...,Insurance,Unknown,3,NaN,Yes,Yes,Yes,No,Yes,No
1,1,Data Scientist,$137K-$171K,4.0,Yes,No,No,Yes,No,No,...,Business Services,$1B-$2B,0,12.0,Yes,Yes,No,No,Yes,Yes
2,2,Data Scientist,$137K-$171K,4.0,No,No,Yes,No,No,No,...,Business Services,$100 M- $500 M,0,NaN,Yes,No,No,Yes,Yes,Yes
3,3,Data Scientist,$137K-$171K,4.0,Yes,No,Yes,No,No,Yes,...,Manufacturing,$100 M- $500 M,3,NaN,Yes,Yes,No,No,No,No
4,4,Data Scientist,$137K-$171K,3.0,Yes,No,No,No,No,No,...,Business Services,Unknown,3,NaN,Yes,No,No,No,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
661,667,Data Scientist,$105K-$167K,4.0,Yes,Yes,No,Yes,No,No,...,Business Services,Unknown,0,NaN,Yes,No,No,No,Yes,Yes
662,668,Data Scientist,$105K-$167K,NaN,No,No,No,No,No,No,...,Unknown,Unknown,0,NaN,No,No,No,No,No,No
663,669,Data Scientist,$105K-$167K,NaN,Yes,Yes,No,Yes,No,No,...,Unknown,Unknown,0,3.0,Yes,No,No,No,Yes,No
664,670,Data Scientist,$105K-$167K,5.0,Yes,No,No,Yes,Yes,Yes,...,Business Services,$1 M- $5 M,0,7.0,Yes,Yes,No,Yes,Yes,Yes
665,671,Data Scientist,$105K-$167K,3.0,Yes,No,No,No,No,No,...,Business Services,$1B-$2B,0,5.0,No,No,No,No,Yes,Yes

In [91]:
#convertir les colonnes binaires (Yes/No) en booleens (True/False)
df[df.columns] = df[df.columns].replace({'Yes': True, 'No': False})

<positron-console-cell-91>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 666 entries, 0 to 665
Data columns (total 34 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 666 non-null    int64
 1   job_title             666 non-null    object
 2   salary_estimate       666 non-null    object
 3   rating                617 non-null    float64
 4   sql                   666 non-null    bool
 5   power_bi              666 non-null    bool
 6   aws                   666 non-null    bool
 7   hadoop                666 non-null    bool
 8   spark                 666 non-null    bool
 9   tensorflow            666 non-null    bool
 10  tableau               666 non-null    bool
 11  microsoft_tools       666 non-null    bool
 12  excel                 666 non-null    bool
 13  python                666 non-null    bool
 14  company_name          666 non-null    object
 15  location              666 non-null    object
 16  location_initials     643 non-null    object
 17  headquarters          666 non-null    object
 18  headquarters_initial  636 non-null    object
 19  size                  666 non-null    object
 20  founded               666 non-null    int64
 21  type_of_ownership     640 non-null    object
 22  publicity             666 non-null    object
 23  industry              666 non-null    object
 24  sector                666 non-null    object
 25  revenue               666 non-null    object
 26  no_of_competitors     666 non-null    int64
 27  yoe                   410 non-null    float64
 28  computer_science      666 non-null    bool
 29  bachelor's            666 non-null    bool
 30  master's              666 non-null    bool
 31  phd                   666 non-null    bool
 32  statistics            666 non-null    bool
 33  mathematics           666 non-null    bool
dtypes: bool(16), float64(2), int64(3), object(13)
memory usage: 104.2+ KB

In [93]:
#Apercu de la nouvelle transformation dans le dataset true/false 
df.head()

,index,job_title,salary_estimate,rating,sql,power_bi,aws,hadoop,spark,tensorflow,...,sector,revenue,no_of_competitors,yoe,computer_science,bachelor's,master's,phd,statistics,mathematics
0,0,Data Scientist,$137K-$171K,3.0,False,False,True,False,False,False,...,Insurance,Unknown,3,NaN,True,True,True,False,True,False
1,1,Data Scientist,$137K-$171K,4.0,True,False,False,True,False,False,...,Business Services,$1B-$2B,0,12.0,True,True,False,False,True,True
2,2,Data Scientist,$137K-$171K,4.0,False,False,True,False,False,False,...,Business Services,$100 M- $500 M,0,NaN,True,False,False,True,True,True
3,3,Data Scientist,$137K-$171K,4.0,True,False,True,False,False,True,...,Manufacturing,$100 M- $500 M,3,NaN,True,True,False,False,False,False
4,4,Data Scientist,$137K-$171K,3.0,True,False,False,False,False,False,...,Business Services,Unknown,3,NaN,True,False,False,False,True,True

In [94]:
#7 filtrer les lignes ou la colonne 'Salary Estimate' est manquante 
salaire_manquant = df[df['salary_estimate'].isna()]

In [95]:
#8 remplacer les valeurs manquantes dans la colonne 'YOE' par la moyenne
df['yoe'] = df['yoe'].fillna(df['yoe'].mean())

In [ ]:
# 9 Supprimer les lignes où 'Rating' est manquante
df.dropna(subset=['rating'], inplace=True)

In [36]:
#10 Créer 'has_phd' (1 si True, sinon 0)
df['has_phd'] = df['phd'].astype(int)

In [ ]:
#diviser la colonne 'Salary Estimate' en deux colonnes 'salary_low' et 'salary_high' en
#utilisant uniquement str.split() et str.replace()
#On nettoie les symboles ($ et K)
clean_salary = df['salary_estimate'].str.replace('$', '').str.replace('K', '')

In [ ]:

df[['salary_low', 'salary_high']] = clean_salary.str.split('-', expand=True)

In [ ]:
#12 Convertir en valeurs numériques
df['salary_low'] = pd.to_numeric(df['salary_low'])
df['salary_high'] = pd.to_numeric(df['salary_high'])

In [40]:
#13 

df['salary_mean'] = (df['salary_low'] + df['salary_high']) / 2

In [41]:
# 14 Calculer l'écart de salaire
df['salary_gap'] = df['salary_high'] - df['salary_low']

In [ ]:
#15 Identifier les écarts > 50K

grands_ecarts = df[df['salary_gap'] > 50]

In [43]:
#16 
df['yoe'].describe()

count    617.000000
mean       4.295387
std        2.235281
min        0.000000
25%        3.000000
50%        4.229268
75%        5.000000
max       20.000000
Name: yoe, dtype: float64

In [44]:
#17. Moyenne, Médiane et Variance de 'Rating'
print(f"Moyenne : {df['rating'].mean()}")
print(f"Médiane : {df['rating'].median()}")
print(f"Variance : {df['rating'].var()}")

Moyenne : 3.9643435980551054
Médiane : 4.0
Variance : 0.4824927908396303

In [46]:
#18. Nombre total d'offres par intitulé de poste
df['job_title'].value_counts()

job_title
Data Scientist                   480
Data Analyst                      53
Data Engineer                     51
Machine Learning Engineer         20
Business Intelligence Analyst      6
Data Modeler                       5
Data Instructor                    1
Data Architect                     1
Name: count, dtype: int64

In [47]:
#Nombre d’entreprises par secteur

df.groupby('sector')['company_name'].nunique()

sector
Accounting & Legal                      2
Aerospace & Defense                    24
Agriculture & Forestry                  2
Biotech & Pharmaceuticals              34
Business Services                      81
Construction, Repair & Maintenance      1
Consumer Services                       1
Education                               2
Finance                                21
Government                             10
Health Care                            17
Information Technology                117
Insurance                              22
Manufacturing                          14
Media                                   5
Non-Profit                              1
Oil, Gas, Energy & Utilities            6
Real Estate                             3
Retail                                  6
Telecommunications                      5
Transportation & Logistics              5
Travel & Tourism                        2
Unknown                                24
Name: company_name, dtype: int64

In [48]:
#19. Nombre moyen de compétiteurs par secteur
df.groupby('sector')['no_of_competitors'].mean()

sector
Accounting & Legal                    0.000000
Aerospace & Defense                   0.608696
Agriculture & Forestry                1.333333
Biotech & Pharmaceuticals             1.015152
Business Services                     0.823009
Construction, Repair & Maintenance    0.000000
Consumer Services                     0.000000
Education                             0.000000
Finance                               0.090909
Government                            0.823529
Health Care                           0.550000
Information Technology                0.809783
Insurance                             0.968750
Manufacturing                         0.913043
Media                                 0.400000
Non-Profit                            0.000000
Oil, Gas, Energy & Utilities          1.300000
Real Estate                           0.000000
Retail                                0.428571
Telecommunications                    0.428571
Transportation & Logistics            1.500000
Travel & Tourism                      0.000000
Unknown                               0.178571
Name: no_of_competitors, dtype: float64

In [ ]:
#21 Compétence la plus demandée
skills = ['python', 'sql', 'aws', 'excel', 'tableau']

df[skills].sum().sort_values(ascending=False)

python     455
sql        339
excel      269
aws        153
tableau    116
dtype: int64

In [98]:
df.columns

Index(['index', 'job_title', 'salary_estimate', 'rating', 'sql', 'power_bi',
       'aws', 'hadoop', 'spark', 'tensorflow', 'tableau', 'microsoft_tools',
       'excel', 'python', 'company_name', 'location', 'location_initials',
       'headquarters', 'headquarters_initial', 'size', 'founded',
       'type_of_ownership', 'publicity', 'industry', 'sector', 'revenue',
       'no_of_competitors', 'yoe', 'computer_science', 'bachelor's',
       'master's', 'phd', 'statistics', 'mathematics'],
      dtype='object')

In [99]:
##22 Pourcentage d’offres demandant Master ou PhD

phd_Perc= df['phd']

In [100]:
Perc= phd_Perc.mean() * 100

In [101]:
print(Perc)

18.76876876876877

In [55]:
#23 Combinaison de compétences la plus fréquente (Data Scientist)
ds = df[df['job_title'] == 'Data Scientist']

ds[skills].astype(int).apply(tuple, axis=1).value_counts().head()

(1, 1, 0, 0, 0)    71
(1, 0, 0, 0, 0)    60
(0, 0, 0, 0, 0)    58
(1, 1, 0, 1, 0)    45
(1, 0, 0, 1, 0)    32
Name: count, dtype: int64

In [56]:
#24 compétence associée aux plus hauts salaires

df.groupby('python')['salary_mean'].mean()

python
False    121.614198
True     122.625275
Name: salary_mean, dtype: float64

In [57]:

df.groupby('sql')['salary_mean'].mean()

sql
False    121.323741
True     123.209440
Name: salary_mean, dtype: float64

In [58]:
#Secteurs demandant le plus de compétences techniques
df['skill_count'] = df[skills].sum(axis=1)
df.groupby('sector')['skill_count'].mean().sort_values(ascending=False)

sector
Consumer Services                     4.000000
Non-Profit                            4.000000
Real Estate                           3.666667
Construction, Repair & Maintenance    3.000000
Media                                 3.000000
Telecommunications                    2.714286
Accounting & Legal                    2.666667
Agriculture & Forestry                2.666667
Finance                               2.515152
Business Services                     2.353982
Transportation & Logistics            2.333333
Retail                                2.285714
Government                            2.235294
Unknown                               2.214286
Insurance                             2.125000
Health Care                           2.100000
Information Technology                2.097826
Manufacturing                         2.086957
Travel & Tourism                      2.000000
Biotech & Pharmaceuticals             1.848485
Aerospace & Defense                   1.782609
Oil, Gas, Energy & Utilities          1.600000
Education                             1.333333
Name: skill_count, dtype: float64

In [59]:
#26 Rating moyen par secteur

df.groupby('sector')['rating'].mean()

sector
Accounting & Legal                    4.333333
Aerospace & Defense                   4.000000
Agriculture & Forestry                3.333333
Biotech & Pharmaceuticals             3.696970
Business Services                     4.000000
Construction, Repair & Maintenance    3.000000
Consumer Services                     4.000000
Education                             3.333333
Finance                               4.000000
Government                            4.058824
Health Care                           3.750000
Information Technology                4.168478
Insurance                             3.656250
Manufacturing                         3.826087
Media                                 4.400000
Non-Profit                            3.000000
Oil, Gas, Energy & Utilities          3.600000
Real Estate                           4.000000
Retail                                3.857143
Telecommunications                    3.285714
Transportation & Logistics            3.166667
Travel & Tourism                      4.000000
Unknown                               4.178571
Name: rating, dtype: float64

In [60]:
#27 Rating moyen par type d’entreprise


df.groupby('type_of_ownership')['rating'].mean()

type_of_ownership
College / University              3.333333
Company                           3.986817
Contract                          4.000000
Government                        4.000000
Hospital                          4.000000
Nonprofit Organization            3.741935
Other Organization                3.600000
Private Practice / Firm           4.000000
Self                              3.000000
Subsidiary or Business Segment    3.928571
Unknown                           5.000000
Name: rating, dtype: float64

In [61]:
#28Salaire moyen par secteur
df.groupby('sector')['salary_mean'].mean()

sector
Accounting & Legal                    124.666667
Aerospace & Defense                   132.695652
Agriculture & Forestry                103.833333
Biotech & Pharmaceuticals             122.871212
Business Services                     127.349558
Construction, Repair & Maintenance     74.750000
Consumer Services                     203.750000
Education                             117.833333
Finance                               115.500000
Government                            134.470588
Health Care                           120.450000
Information Technology                118.902174
Insurance                             111.281250
Manufacturing                         123.239130
Media                                 155.300000
Non-Profit                             43.500000
Oil, Gas, Energy & Utilities          101.300000
Real Estate                           116.833333
Retail                                150.142857
Telecommunications                    112.357143
Transportation & Logistics            117.750000
Travel & Tourism                      128.666667
Unknown                               121.517857
Name: salary_mean, dtype: float64

In [62]:
#29 Salaire moyen par État

df.groupby('location_initials')['salary_mean'].mean()

location_initials
AL              131.125000
AZ              140.875000
Anne Arundel     89.000000
CA              118.550000
CO              103.650000
CT               98.125000
DC              139.500000
DE              271.500000
FL              118.437500
GA              109.666667
IA              140.833333
IL              120.362069
IN              113.400000
KS              103.000000
LA              103.000000
MA              119.677966
MD              112.974359
MI              119.000000
MN               94.000000
MO              114.958333
MS              133.000000
NC              150.111111
NE              104.500000
NH              132.000000
NJ              120.600000
NY              132.864583
OH              103.772727
OK               68.000000
OR              132.000000
PA              122.318182
RI              130.750000
SC               96.000000
TN              102.187500
TX              136.058824
UT              104.833333
VA              128.442308
WA              134.700000
WI              144.416667
WV              114.000000
Name: salary_mean, dtype: float64

In [63]:
#30 Entreprises offrant les salaires moyens les plus élevés

df.groupby('company_name')['salary_mean'].mean().sort_values(ascending=False).head()

company_name
Alaka`ina Foundation Family of Companies    271.5
Aptive                                      271.5
Roche                                       271.5
Sharpedge Solutions Inc                     271.5
Creative Circle                             271.5
Name: salary_mean, dtype: float64

In [64]:
#31 Tableau croisé Job title × Sector (nombre d’offres)

pd.crosstab(df['job_title'], df['sector'])

sector,Accounting & Legal,Aerospace & Defense,Agriculture & Forestry,Biotech & Pharmaceuticals,Business Services,"Construction, Repair & Maintenance",Consumer Services,Education,Finance,Government,...,Manufacturing,Media,Non-Profit,"Oil, Gas, Energy & Utilities",Real Estate,Retail,Telecommunications,Transportation & Logistics,Travel & Tourism,Unknown
job_title,,,,,,,,,,,,,,,,,,,,,
Business Intelligence Analyst,0,0,0,0,0,0,0,0,0,0,...,3,0,0,0,0,0,0,1,0,0
Data Analyst,0,0,0,3,8,0,0,0,11,0,...,4,1,0,2,0,0,1,0,0,1
Data Architect,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
Data Engineer,0,1,0,1,10,0,0,0,7,2,...,1,1,0,1,0,0,0,0,0,1
Data Instructor,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Data Modeler,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
Data Scientist,3,38,3,62,95,2,2,1,14,13,...,14,3,1,7,3,7,6,5,3,26
Machine Learning Engineer,0,7,0,0,0,0,0,2,0,2,...,0,0,0,0,0,0,0,0,0,0

In [65]:
#32 Tableau croisé Rating moyen Industry × Sector


pd.pivot_table(
    df,
    values='rating',
    index='industry',
    columns='sector',
    aggfunc='mean'
)

sector,Accounting & Legal,Aerospace & Defense,Agriculture & Forestry,Biotech & Pharmaceuticals,Business Services,"Construction, Repair & Maintenance",Consumer Services,Education,Finance,Government,...,Manufacturing,Media,Non-Profit,"Oil, Gas, Energy & Utilities",Real Estate,Retail,Telecommunications,Transportation & Logistics,Travel & Tourism,Unknown
industry,,,,,,,,,,,,,,,,,,,,,
Accounting,4.333333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Advertising & Marketing,NaN,NaN,NaN,NaN,3.782609,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aerospace & Defense,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Architectural & Engineering Services,NaN,NaN,NaN,NaN,3.666667,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Banks & Credit Unions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.875000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Biotech & Pharmaceuticals,NaN,NaN,NaN,3.69697,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Cable, Internet & Telephone Providers",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN
Chemical Manufacturing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Colleges & Universities,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.333333,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Computer Hardware & Software,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Construction,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Consulting,NaN,NaN,NaN,NaN,4.083333,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Consumer Electronics & Appliances Stores,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,NaN
Consumer Products Manufacturing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.600000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Department, Clothing, & Shoe Stores",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,NaN
Electrical & Electronic Manufacturing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Energy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,NaN
Enterprise Software & Network Solutions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Express Delivery Services,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN
Farm Support Services,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Federal Agencies,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.125,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Financial Transaction Processing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Food & Beverage Manufacturing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Food & Beverage Stores,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,NaN
Health Care Services & Hospitals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Health, Beauty, & Fitness",NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Hotels, Motels, & Resorts",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
IT Services,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Industrial Manufacturing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Insurance Agencies & Brokerages,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Insurance Carriers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Internet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Investment Banking & Asset Management,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.769231,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.500000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Logistics & Supply Chain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN
Miscellaneous Manufacturing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
News Outlet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Oil & Gas Services,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,NaN
Other Retail Stores,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.666667,NaN,NaN,NaN,NaN
Publishing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rail,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN
Real Estate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN
Research & Development,NaN,NaN,NaN,NaN,3.916667,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Shipping,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN
Social Assistance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Staffing & Outsourcing,NaN,NaN,NaN,NaN,4.194444,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
State & Regional Agencies,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Telecommunications Manufacturing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN
Telecommunications Services,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.4,NaN,NaN,NaN
Timber Operations,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Transportation Equipment Manufacturing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Transportation Management,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
Travel Agencies,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.178571
Utilities,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.333333,NaN,NaN,NaN,NaN,NaN,NaN
Venture Capital & Private Equity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Video Games,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,4.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Wholesale,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
#33 Proportion d’offres demandant Python par État

pd.crosstab(
    df['location_initials'],
    df['python'],
    normalize='index')

python                False     True
location_initials
AL                 0.250000  0.750000
AZ                 0.500000  0.500000
Anne Arundel       1.000000  0.000000
CA                 0.157143  0.842857
CO                 0.300000  0.700000
CT                 0.000000  1.000000
DC                 0.269231  0.730769
DE                 0.000000  1.000000
FL                 0.000000  1.000000
GA                 0.000000  1.000000
IA                 1.000000  0.000000
IL                 0.482759  0.517241
IN                 0.000000  1.000000
KS                 0.000000  1.000000
LA                 1.000000  0.000000
MA                 0.338983  0.661017
MD                 0.282051  0.717949
MI                 0.200000  0.800000
MN                 0.750000  0.250000
MO                 0.083333  0.916667
MS                 1.000000  0.000000
NC                 0.666667  0.333333
NE                 0.500000  0.500000
NH                 0.000000  1.000000
NJ                 0.500000  0.500000
NY                 0.125000  0.875000
OH                 0.272727  0.727273
OK                 1.000000  0.000000
OR                 0.000000  1.000000
PA                 0.454545  0.545455
RI                 1.000000  0.000000
SC                 1.000000  0.000000
TN                 0.125000  0.875000
TX                 0.176471  0.823529
UT                 0.000000  1.000000
VA                 0.243590  0.756410
WA                 0.533333  0.466667
WI                 0.666667  0.333333
WV                 0.000000  1.000000

In [68]:
#34 Salaire moyen par Company Name et Job title


pd.pivot_table(
    df,
    values='salary_mean',
    index='company_name',
    columns='job_title',
    aggfunc='mean'
)

job_title,Business Intelligence Analyst,Data Analyst,Data Architect,Data Engineer,Data Instructor,Data Modeler,Data Scientist,Machine Learning Engineer
company_name,,,,,,,,
1-800-Flowers,NaN,NaN,NaN,NaN,NaN,NaN,203.75,NaN
1010data,NaN,NaN,NaN,107.0,NaN,NaN,NaN,NaN
10x Genomics,NaN,NaN,NaN,NaN,NaN,NaN,271.50,NaN
1904labs,NaN,NaN,NaN,NaN,NaN,NaN,126.75,NaN
22nd Century Technologies,NaN,NaN,NaN,NaN,NaN,NaN,113.00,NaN
...,...,...,...,...,...,...,...,...
eBay,NaN,NaN,NaN,NaN,NaN,NaN,120.50,NaN
hc,NaN,NaN,NaN,115.5,NaN,NaN,NaN,NaN
iRobot,NaN,NaN,NaN,NaN,NaN,NaN,129.50,NaN
iSeatz,NaN,103.0,NaN,NaN,NaN,NaN,NaN,NaN
webfx.com,NaN,76.5,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
#35 Nombre moyen de compétiteurs par secteur et industrie


pd.pivot_table(
    df,
    values='no_of_competitors',
    index='sector',
    columns='industry',
    aggfunc='mean'
)

industry,Accounting,Advertising & Marketing,Aerospace & Defense,Architectural & Engineering Services,Banks & Credit Unions,Biotech & Pharmaceuticals,"Cable, Internet & Telephone Providers",Chemical Manufacturing,Colleges & Universities,Computer Hardware & Software,...,Telecommunications Services,Timber Operations,Transportation Equipment Manufacturing,Transportation Management,Travel Agencies,Unknown,Utilities,Venture Capital & Private Equity,Video Games,Wholesale
sector,,,,,,,,,,,,,,,,,,,,,
Accounting & Legal,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aerospace & Defense,NaN,NaN,0.608696,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Agriculture & Forestry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Biotech & Pharmaceuticals,NaN,NaN,NaN,NaN,NaN,1.015152,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Business Services,NaN,1.304348,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
"Construction, Repair & Maintenance",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Consumer Services,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Education,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Finance,NaN,NaN,NaN,NaN,0.375,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
Government,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Health Care,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Information Technology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.649123,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Insurance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Manufacturing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.666667,NaN
Non-Profit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Oil, Gas, Energy & Utilities",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
Real Estate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Retail,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Telecommunications,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Transportation & Logistics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
Travel & Tourism,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.178571,NaN,NaN,NaN,NaN

In [70]:
#36 Lien entre rating et nombre de compétences

df[['rating', 'skill_count']].corr()

               rating  skill_count
rating       1.000000    -0.067158
skill_count -0.067158     1.000000

In [71]:
#37 Top 10 États les plus attractifs

state_score = df.groupby('location_initials')[['rating', 'salary_mean']].mean()
state_score.sort_values(['rating', 'salary_mean'], ascending=False).head(10)

                     rating  salary_mean
location_initials
IA                 5.000000   140.833333
UT                 4.666667   104.833333
WI                 4.333333   144.416667
MO                 4.250000   114.958333
CT                 4.250000    98.125000
MD                 4.205128   112.974359
VA                 4.128205   128.442308
GA                 4.111111   109.666667
MA                 4.101695   119.677966
CO                 4.100000   103.650000

In [72]:
#38 Profil type d’une offre Data Scientist

ds = df[df['job_title'] == 'Data Scientist']

ds[['yoe', 'rating', 'salary_mean', 'skill_count']].mean()

yoe              4.336280
rating           3.954167
salary_mean    124.550000
skill_count      2.102083
dtype: float64

In [73]:
#39 Entreprises fondées avant 2000 avec salaire moyen > 120K


df[
    (df['founded'] < 2000) &
    (df['salary_mean'] > 120)
][['company_name', 'salary_mean']]

             company_name  salary_mean
0             Healthfirst        154.0
1                 ManTech        154.0
2          Analysis Group        154.0
4      Affinity Solutions        154.0
6                Novartis        154.0
..                    ...          ...
655   Qurate Retail Group        136.0
656       SolutionIT, Inc        136.0
661              TRANZACT        136.0
664  ChaTeck Incorporated        136.0
665         1-800-Flowers        136.0

[147 rows x 2 columns]

In [74]:
#40 Top 5 entreprises privées avec le plus d’offres


df[df['type_of_ownership'] == 'Private'].company_name.value_counts().head(5)

Series([], Name: count, dtype: int64)